spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration


cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key:
      secret-key:
    sns:
      snsRegion: us-east-2
      resSnsTopicArn:
      reqSnsTopicArn:
    sqs:
      sqsRegion: us-east-2
      sqsTopicArn:
      uri:
    dynamodb:
      region: us-east-2
      serviceEndpoint:
