package com.miteshpv.bizprofileservice.bizprofile.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "entitlement")
public class ProductEntitlementEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String entitlementId;

    @DynamoDBAttribute
    private String entitledProdCode;

    @DynamoDBAttribute
    private String personTaxId;
}
