server.port: 8082

spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAWXCOGRBULKGXYMCS
      secret-key: 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
    sns:
      snsRegion: us-east-2
      resSnsTopicArn: arn:aws:sns:us-east-2:461872990312:biz-profile-res
      reqSnsTopicArn: arn:aws:sns:us-east-2:461872990312:biz-profile-req
    sqs:
      sqsRegion: us-east-2
      sqsTopicArn: arn:aws:sqs:us-east-2:461872990312:qb-payroll-sqs
      uri: https://sqs.us-east-2.amazonaws.com/461872990312/qb-payroll-sqs

product:
  name: Quibooks Payroll
  code: QB-PRL